### ISSUE TITLE
Update the nbdev version to nbdev2

### ISSUE THREAD

**Issue by butchtm** [thinkingmachines/geowrangler#111]
This will improve the doc site aesthetics  (see [new nbdev](https://nbdev.fast.ai)) 
* replaces jekyll w/ quarto for site generation
* removes need for custom nbdev (since black formatting is already implemented in nbdev2)
* lots of other improvements

Caveats:
* some features (e.g. source links) are still being worked on
* nbdev2 commands have changed slightly and will require readjustments esp. w/ GH workflows.
* need to test the update thoroughly before deploying to prod.

**Comment by tm-kah-alforja** [comment]
on pause; waiting for updates on missing features

**Comment by joshuacortez** [comment]
@butchtm migration to nbdev2 is fully done right? I'm closing this issue
