### ISSUE TITLE
Area zonal stats: using imputed_mean results to nulls even if fillna=True

### ISSUE THREAD

**Issue by alronlam** [thinkingmachines/geowrangler#134]
![code](https://user-images.githubusercontent.com/1049495/185225796-e9ece7fa-51f9-4310-8492-83882e5b9764.PNG)

_Look at the `d_mbps_mean`column_
![imputed_mean_nulls](https://user-images.githubusercontent.com/1049495/185225727-29fcbdaf-435b-41d3-84e8-b655555b835c.PNG)

**Comment by butchtm** [comment]
hi @alronlam sorry for the late reply, but can you share the notebook/gist to replicate this issue as I haven't been able to replicate this. tia!
![image](https://user-images.githubusercontent.com/82074733/186852101-d03bdff5-1e51-4057-881a-ad43dba35d0b.png)

**Comment by butchtm** [comment]
hi @alronlam I was able to finally recreate the problem and find the source.
Fix to this is on the way. Will update soon.
