### ISSUE TITLE
Link to tutorial.dhs.html is not working 

### ISSUE THREAD

**Issue by jtmiclat** [thinkingmachines/geowrangler#158]
https://geowrangler.thinkingmachin.es/tutorial.dhs.html is returning a 404

**Comment by butchtm** [comment]
Could you recheck? Works for me... @jtmiclat 
![image](https://user-images.githubusercontent.com/82074733/188043927-28b66432-45c6-447d-8891-a54be870aaa9.png)

**Comment by butchtm** [comment]
please refile if still not working

**Comment by jtmiclat** [comment]
seems to be working now!
