### ISSUE TITLE
grids.BingTileGridGenerator.generate_grid_join crashing when running with zoom 18

### ISSUE THREAD

**Issue by janzkyle** [thinkingmachines/geowrangler#218]
In [01_aoi_grids_zoom18.ipynb](https://github.com/thinkingmachines/geo-retail-demo-data-processing/blob/master/notebooks/01_AOI_generation/01_aoi_grids_zoom18.ipynb), changing the zoom level from 16 to 18 crashes after running the `generate_grid_join()` for around 30 mins

Error log:
```
Cannot execute code, session has been disposed. Please try restarting the Kernel.
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.
```

**Comment by joshuacortez** [comment]
You can now use the `FastBingTileGenerator.generate grid` method with parameter `unique_id_col` to do this much more efficiently now. See sample usage [here](https://geowrangler.thinkingmachin.es/tutorial.grids.html#fast-bing-tile-grid-generator)
