### ISSUE TITLE
Support for Pandas 2.x in requirements

### ISSUE THREAD

**Issue by joshuacortez** [thinkingmachines/geowrangler#221]
Pandas 2.x has been out for a while. The last time Pandas 1.x was updated was [Jan 2023](https://pandas.pydata.org/docs/whatsnew/v1.5.3.html). 

In the [pyproj.toml file](https://github.com/thinkingmachines/geowrangler/blob/master/pyproject.toml) there's still a hard dependency for pandas to be <2. Could we loosen this restriction to accommodate for Pandas 2.x?

**Comment by tm-danna-ang** [comment]
Addressed in #224
