### ISSUE TITLE
add github releases

### ISSUE THREAD

**Issue by joshuacortez** [thinkingmachines/geowrangler#230]
We can consider using [github releases](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) for geowrangler so our users can be informed about the latest geowrangler version. Here's a [sample from the scikit-learn library.](https://github.com/scikit-learn/scikit-learn/releases/tag/1.5.0)

**Comment by joshuacortez** [comment]
from @butchtm 

> [nbdev](https://nbdev.fast.ai/api/release.html) has a nbdev_release_gh command that automates this for you.
> we can even release to conda now (just haven't had the time to explore it)

**Comment by butchtm** [comment]
added[ release tags here](https://github.com/thinkingmachines/geowrangler/releases)
