### ISSUE TITLE
Updates to DEVELOPMENT.md

### ISSUE THREAD

**Issue by tm-jc-nacpil** [thinkingmachines/geowrangler#232]
I noticed that in the contributing section, the paragraphs are enclosed in code blocks but the actual code lines are not. This seems to stem from a stray ``` before the actual codeblocks See line:

https://github.com/thinkingmachines/geowrangler/blob/1cfb0d1ea7774896b897de87670bea85c4b65225/DEVELOPMENT.md?plain=1#L36

This makes the content confusing to read when reading the rendered markdown.

**Comment by butchtm** [comment]
@tm-jc-nacpil yes the new command is `nbdev_install_hooks` in nbdev2. 
Fixed this issue in #234

**Comment by joshuacortez** [comment]
I think we forgot to change `nbdev_install_hooks` in the new DEVELOPMENT markdown in #234 . Will file a separate PR
