### ISSUE TITLE
Move dhs.py from geowrangler dir to geowrangler/datasets dir

### ISSUE THREAD

**Issue by joshuacortez** [thinkingmachines/geowrangler#244]
The [dhs.py script](https://github.com/thinkingmachines/geowrangler/blob/master/geowrangler/dhs.py) seems out of place since it's not in the `datasets` subdirectory along with `geofabrik.py`, `nightlights.py`, and `ookla.py`. Might be good to move its location

**Comment by butchtm** [comment]
hi @joshuacortez -- our original rationale was that unlike the other dataset related modules -- this module not actually about downloading the dhs data, but for manipulating DHS data -- unlike the other datasets, DHS data is not available publicly so we cannot provide utils for downloading it but instead each user must request it from the source. 

The utilities provided are for massaging the provided data in such a way as to make it easier to manage for downstream activities such as building training/validation data for ML models. 

Despite this, @tm-danna-ang @joshuacortez  @tm-jc-nacpil feel free to chime if you feel strongly that it would be better to leave it stand alone or moved to the datasets module.

**Comment by joshuacortez** [comment]
Thanks for explaining the rationale @butchtm !

I don't feel super strongly about it, but just thought that dataset-specific scripts (regardless of its just for download or also for manipulation) are together in the same directory

Curious to hear others' thoughts

**Comment by joshuacortez** [comment]
ok let's keep it as is then!
