### ISSUE TITLE
Grids tutorial fails due to Geopandas version 0.14.4  error Attribute Error:  'GeoDataFrame' object has no attribute 'union_all' 

### ISSUE THREAD

**Issue by butchtm** [thinkingmachines/geowrangler#248]
<img width="485" alt="image" src="https://github.com/user-attachments/assets/b381330b-da36-4ad7-acc1-d80b8bc2dbc1">

**Workaround**: Upgrade geopandas to 1.0 

**To fix**: Pin geopandas to >=1.0 in `settings.ini` which will force the upgrade.

**Comment by joshuacortez** [comment]
Oh thanks for the catch @butchtm !
