### ISSUE TITLE
Distinguishing between grids and tiles

### ISSUE THREAD

**Issue by joshuacortez** [thinkingmachines/geowrangler#34]
This might be pedantic, but what do you think about distinguishing between `grids` and `grid tile` for added clarity? 

- Grid Tile (or tile): a single square
- Grid: the collection of squares

This will imply some renaming in the `GridGenerator` class

**Comment by jtmiclat** [comment]
I reserved the term `Tile` to refer to any division and `Grid` specifically to 90degree angled divisions. So further down the line, we can include generating h3 and h2 grids/tiles.

Further investigation both h3 and s2 refers to its divisions as cells. This might be based of cellular geography https://link.springer.com/chapter/10.1007/978-94-009-9394-5_18

This leaves us with the following 
`[Shape]Cell` - SquareCell, H3Cell, S2Cell refers to a single polygon represented in a map. 
`[Shape]Grid` - SquareGrid, H3 Grid, S2Grid refers to a collection of cells

This would mean we would rename `GridGenerator` to `SquareGridGenerator`.

What do you think?

**Comment by joshuacortez** [comment]
Cool, my first time to hear about [h2](https://s2geometry.io/)

Sounds good! I'm just thinking about how intuitive the names are to first-time users, but the `[Shape]Cell` and `[Shape]Grid` format sound clear to me.
