### ISSUE TITLE
Change default fillna to be false and allow configurable  fill value

### ISSUE THREAD

**Issue by jtmiclat** [thinkingmachines/geowrangler#64]
### Discussed in https://github.com/thinkingmachines/geowrangler/discussions/62

<div type='discussions-op-text'>

<sup>Originally posted by **mosesckim** June 30, 2022</sup>
Noticed default is to fill NaNs with zero after aggregation; this might make it difficult to identify original NaNs if there are actual zeros in the aggregation.

https://github.com/thinkingmachines/geowrangler/blob/master/geowrangler/vector_zonal_stats.py#L205

Also, a suggestion would be, in the case `fillna` option is set to True, make the replacement value (0 in this case at the moment) a variable users can input (e.g. -1, etc.)

Thanks!
Moses</div>

**Comment by butchtm** [comment]
I'm setting this a good first issue for new contributors!

**Comment by butchtm** [comment]
Implemented in #94
