### ISSUE TITLE
Vector Zonal Stats: Error when aligning OSM POIs to an Indonesian Regency

### ISSUE THREAD

**Issue by alronlam** [thinkingmachines/geowrangler#70]
**Colab notebook for testing:**
*  https://colab.research.google.com/drive/147HWUgaBztsZuBPrI_HTckBrz_vl9l1l?usp=sharing 

**Scenario:**
* Created an AOI GDF representing the Subang Regency of Indonesia.
* Tried simply counting the POIs within this area, but got the error seen in the screenshot:

![gw_aoi_index_error](https://user-images.githubusercontent.com/1049495/177067610-5c98c9c3-1b98-4411-878f-b429b71d0ade.PNG)

![gw_aoi_index_error_full_stacktrace](https://user-images.githubusercontent.com/1049495/177067644-d4573bb0-4747-4d81-8623-cbfead42f431.PNG)

Could it be a typo? Since the key error mentions "GeoWrangl**ee**r_aoi_index"

In case it's relevant, noting that the function works when I passed in grid tiles instead of the Subang Regency gdf itself. 
![gw_aoi_works](https://user-images.githubusercontent.com/1049495/177067839-1e036038-ff21-4dc0-ad78-f4e137da3943.PNG)

**Comment by jtmiclat** [comment]
This error stems from us no supporting multiindex GeoDataFrames and dissolving generating a multiindex GeoDataFrame
```
aoi = idn[idn.ADM2_EN == "Subang"].dissolve(by="ADM2_EN")
```
Converting the above to 
```
aoi = idn[idn.ADM2_EN == "Subang"]
```
works.

**Comment by jtmiclat** [comment]
Alternatively, you can pass `as_index` as False and this doesn't generate a MultiIndex GeoDataFrame
```
aoi = idn[idn.ADM2_EN == "Subang"].dissolve(by="ADM2_EN", as_index=False)

```

**Comment by jtmiclat** [comment]
@butchtm @alronlam Should we support multiindex geodataframes or should we throw an assertion error telling users that we dont support it?

**Comment by butchtm** [comment]
@jtmiclat @alronlam 

For now, we could do a quick fix to throw an assertion error so users are aware we don't support multi-index for now.

Then file an enhancement request to support multi-indexes separately later.  cc @tm-kah-alforja

**Comment by alronlam** [comment]
Ahh I see. Agree with @butchtm  I think we can just throw an assertion error for now so it's clear what the error is and how to fix it. I'm not really sure either if multi-index support is something that's necessary.

**Comment by jtmiclat** [comment]
Alright, i can take this on.

**Comment by butchtm** [comment]
Reopening this. Still reproducible error when I tried today. See this[ updated gist](https://gist.github.com/butchtm/5574aaf99aee32f1a7f1158ca1218018).
