### ISSUE TITLE
Geometry Validation: Catching polygons with less than 3 unique vertices

### ISSUE THREAD

**Issue by joshuacortez** [thinkingmachines/geowrangler#88]
This could be a feature to consider for Geowrangler Geometry Validation

I encountered an error where I tried to upload a geopandas dataframe to BQ and it said 

> GenericGBQException: Reason: 400 Error while reading data, error message: Invalid geography value for column 'geometry', error: Polygon loop should have at least 3 unique vertices, but only had 2; in WKB geography

It turns out there was a "polygon" that was actually a line. I verified it by computing the area which was actually 0.

> 'POLYGON ((122.95320551089915 11.473736609261481, 122.952381 11.4737421, 122.95320551089915 11.47373660926148, 122.95320551089915 11.473736609261481))'

The weird thing is it's not caught by `is_valid` on the epsg:4326 GeoSeries but it's caught by `is_valid` when the GeoSeries was projected to epsg:3123. I expected `is_valid` to return FALSE even if the polygon was not projected.

Perhaps this can be something geowrangler's geometry validation can also catch?

**Comment by jtmiclat** [comment]
We actually have a broken polygon for slivers in `data/broker.geojson`
```
    {
      "type": "Feature",
      "properties": {
        "id": "slither"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              0.0,
              0.0
            ],
            [
              0.0,
              1.0
            ],
            [
              0.0,
              0.0
            ]
          ]
        ]
      }
    },
```

A way to detect this is by getting the polygon area but this is a bit hard to deal with for different projections would imply different threshold areas to consider as there won't necessarily return zero. 


Btw the polygon you listed isnt a straight line? 
```
In [36]: wkt.loads("POLYGON ((122.95320551089915 11.473736609261481, 122.952381 11.4737421, 122.95320551089915 11.47373660926148, 122.95320551089915 11.473736609261481))").area
Out[36]: 7.323127874328026e-19
```

**Comment by joshuacortez** [comment]
Oh I computed the area on the projected polygon. Maybe it's a precision thing. The sample broken polygon you mentioned seems good!

**Comment by jtmiclat** [comment]
> recognized source of error since overlay was first invented in the 1970s.
nice. 

I think we can catch the area being 0 as a default and if the user has more of a threshold they can build their own validator
```
from geowrangler.validation import BaseValidator

class AreaValidator(BaseValidator):
    validator_column_name = "area_is_not_almost_zero"
    fix_available = False  # Telling the validator that there is no available fixes
    warning_message = "Found geometries with area almost zero"  # warning message
    geometry_types = ["Polygon", "MultiPolygon"]  # What kind of geometies to validate and fix

    def check(self, geometry):
        # Checks if the geometry is valid. If False, warn the user
        return geometry.area > 0.0000001 # or whatever threshold they have 

validated_gdf = AreaValidator().validate(gdf)
```

**Comment by joshuacortez** [comment]
Yep agree!
